services:
  # 1. The Frontend (Next.js)
  - type: web
    name: zpt-cinema-web
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: TMDB_API_KEY
        sync: false # User must input this in the dashboard

  # 2. The Engine (MeTube Docker)
  - type: web
    name: zpt-cinema-engine
    env: docker
    plan: free
    dockerContext: ./backend
    dockerFilePath: ./backend/Dockerfile
    envVars:
      - key: PORT
        value: 8081
